xxl:
  job:
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: ''
    ### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
    i18n: zh_CN
    admin:
      ## （转移到基础配置文件中）
      ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#      addresses: http://127.0.0.1:8888
    executor:
      ## （转移到基础配置文件中）
#      address: http://127.0.0.1:8888
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appName: smart-job
      ### 执行器名称 [选填]
      title: 执行器
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: ''
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      ## （转移到基础配置文件中）
#      logPath: F:\xxl_logs\job
      ### 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      logRetentionDays: 30
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
    ## xxl-job, triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    ### xxl-job, log retention days
    logRetentionDays: 30