server:
  port: 8888
spring:
###### 数据库 ######
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart-demo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowmultiqueries=true&nullCatalogMeansCurrent=true
    username: # 账号
    password: # 密码
###### Redis ######
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    password:
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms  # 关闭超时时间
    database: 7
###### Xxl Job ######
xxl:
  logPath: F:\xxl_logs\job  # 日志输出地址
  executor:
    port: 9999 # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；