server:
  maxHttpHeaderSize: 1024000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: demo
    include: core,mybatis,druid,xxl,pool,camunda
  application:
    name: smart-boot (demo)
## Xxl-Job开启状态
job:
  openStatus: true