server:
  port: 8888
spring:
###### 数据库  ######
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze37j6mw545r0y62jo.mysql.rds.aliyuncs.com:3306/smart-demo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowmultiqueries=true&nullCatalogMeansCurrent=true
    username: pst_mysql
    password: 1qaz2wsx==
###### Redis  ######
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    password:
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms  # 关闭超时时间
    database: 7
###### Xxl Job ######
xxl:
  logPath: F:\xxl_logs\job  # 日志输出地址
  admin:
    addresses: http://127.0.0.1:8888
  executor:
    address: ''